### ISSUE TITLE
NoSuchMethodError : method not found: 'members' on latest dev channel build

### ISSUE THREAD

**Issue by Andersmholmgren** [justinfagnani/dado#15]
Works on stable

Exception message

  Test failed: Caught Class '_LocalClassMirror' has no instance getter 'members'.

  NoSuchMethodError : method not found: 'members'
  Receiver: Instance of '_LocalClassMirror'
  Arguments: []
  dart:core-patch/object_patch.dart 45                                                    Object.noSuchMethod
  package:dado/dado.dart 245:16                                                           _registerBindings
  dart:core-patch/growable_array.dart 240                                                 List.forEach
  package:dado/dado.dart 147:20

**Comment by Dreckr** [comment]
Does this happen with latest Dart? Pub's version is not up to date as we have made some changes and there is no call to 'members' on a ClassMirror anymore. Please, try using git as source (https://github.com/dart-lang/dado.git).

If it still doesn't work, could you build a small test case or describe how you've reached such error?

**Comment by Andersmholmgren** [comment]
Yes it happens on latest dev channel but not latest stable channel.

The git source works. Are you planning on releasing to pub at any point soon?

**Comment by Dreckr** [comment]
Well, I don't manage this project, but I think a new version will be put on pub as soon as it becomes good to public use. Hopefully, that won't take too long.

**Comment by justinfagnani** [comment]
I'll update the pub version ASAP since it's broken. I think we're probably a bit stable in terms of API still though, so apologies for that.

**Comment by Andersmholmgren** [comment]
Great. Thanks Justin. I've switched to the git link for now so no urgency
